### ISSUE TITLE
Relax data checking on payload

### ISSUE THREAD

**Issue by chicco785** [orchestracities/ngsi-timeseries-api#141]
we should avoid not storing data when a single attribute is not valid, we should just drop that value, raise a warning (possibly also in the response) and store the rest. @c0c0n3 @taliaga what do you think?

```
INFO:reporter.reporter:Received payload: {'id': '161', 'type': 'WasteContainer', 'TimeInstant': {'type': 'ISO8601', 'value': ' ', 'metadata': {}}, 'address': {'type': 'Text', 'value': ' ', 'metadata': {}}, 'dateLastEmptying': {'type': 'Text', 'value': '2019-01-22 13:01:27', 'metadata': {}}, 'dateModified': {'type': 'DateTime', 'value': '1970-01-01T00:00:00.000Z', 'metadata': {}}, 'description': {'type': 'Text', 'value': ' ', 'metadata': {}}, 'deviceHeight': {'type': 'Number', 'value': '160', 'metadata': {}}, 'fillingLevel': {'type': 'Number', 'value': 0.89499734, 'metadata': {}}, 'location': {'type': 'geo:point', 'value': '0, 0', 'metadata': {}}, 'locationDescription': {'type': 'Text', 'value': ' ', 'metadata': {}}, 'proximity': {'type': 'Number', 'value': ' ', 'metadata': {}}, 'simulated': {'type': 'Boolean', 'value': ' ', 'metadata': {}}, 'site': {'type': 'Text', 'value': ' ', 'metadata': {}}, 'status': {'type': 'Text', 'value': 'dropped', 'metadata': {}}, 'storedWasteKind': {'type': 'Text', 'value': ' ', 'metadata': {}}, 'temperature': {'type': 'Number', 'value': ' ', 'metadata': {}}, 'utm_e': {'type': 'Text', 'value': ' ', 'metadata': {}}, 'utm_n': {'type': 'Number', 'value': ' ', 'metadata': {}}}
[2019-01-25 13:01:27,631] ERROR in app: Exception on /v2/notify [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/connexion/decorators/decorator.py", line 73, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.6/site-packages/connexion/decorators/uri_parsing.py", line 117, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.6/site-packages/connexion/decorators/validation.py", line 163, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.6/site-packages/connexion/decorators/validation.py", line 336, in wrapper
    return function(request)
  File "/usr/local/lib/python3.6/site-packages/connexion/decorators/decorator.py", line 44, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.6/site-packages/connexion/decorators/parameter.py", line 207, in wrapper
    return function(**kwargs)
  File "/src/ngsi-timeseries-api/src/reporter/reporter.py", line 148, in notify
    trans.insert([payload], fiware_s, fiware_sp)
  File "/src/ngsi-timeseries-api/src/translators/crate.py", line 181, in insert
    fiware_servicepath)
  File "/src/ngsi-timeseries-api/src/translators/crate.py", line 279, in _insert_entities_of_type
    self.cursor.executemany(stmt, entries)
  File "/usr/local/lib/python3.6/site-packages/crate/client/cursor.py", line 67, in executemany
    self.execute(sql, bulk_parameters=seq_of_parameters)
  File "/usr/local/lib/python3.6/site-packages/crate/client/cursor.py", line 54, in execute
    bulk_parameters)
  File "/usr/local/lib/python3.6/site-packages/crate/client/http.py", line 328, in sql
    content = self._json_request('POST', self.path, data=data)
  File "/usr/local/lib/python3.6/site-packages/crate/client/http.py", line 448, in _json_request
    _raise_for_status(response)
  File "/usr/local/lib/python3.6/site-packages/crate/client/http.py", line 187, in _raise_for_status
    error_trace=error_trace)
crate.client.exceptions.ProgrammingError: SQLActionException[ColumnValidationException: Validation failed for simulated: Cannot cast ' ' to type boolean]
```

**Comment by chicco785** [comment]
we should probably make a list of cases:
* type number and value string, cast to number if possible, if not set to null (would that work?)
* type boolean and value not boolean,  cast to boolean if possible, if not set to null (would that work?)
* type datetime and value not datetime,  cast to datetime if possible, if not set to null (would that work?)

**Comment by c0c0n3** [comment]
this issue goes hand-in-hand with #152.

**Comment by chicco785** [comment]
see PR #449
