### ISSUE TITLE
Discard attribute on type mismatch

### ISSUE THREAD

**Issue by c0c0n3** [orchestracities/ngsi-timeseries-api#241]
### The problem
The first time we see an entity we create a corresponding table in the DB. Attributes get mapped to columns and the column type gets derived from the attribute's NGSI type if present or inferred by QL if the attribute has no type. Then attribute values get stored in the table according to their types. From this point on, we expect attributes we've seen already to always have the same type as in the first notification. If later on we get an entity notification containing an attribute we've already mapped but with a different type, QL bombs out on inserting the entity into the table since the DB rejects it due to a type mismatch. So we end up ditching the whole notification.

### Proposed solution
Discard attributes whose type doesn't match the column type and store the rest of the data. This is better than storing no data at all, but see below for other options.

### Alternatives
We may also consider adding data conversions when possible so that if e.g. an attribute was originally stored as a number and then comes in as a string, we attempt converting the string to a number and only discard the value if the conversion fails. See also the following issues:

* #225: Support use of " wrapping fromDate and toDate
* #224: First-time null values taken as object attributes

Another approach is to append the NGSI attribute type to the column name so that even if the NGSI type changes, we're still able to store the attribute value. For example if an attribute named `my_attr` has an initial type of `Number` and then the type becomes `Text`, we'll store values in two columns, respectively: `my_attr_number` and `my_attr_text`. While this is bomb proof with respect to storing data, it could make it difficult to query data---e.g. what would be the average value of `my_attr` over a time interval that happens to contain both numeric and textual representations? 

### Additional context
Here's an example of a notification we failed to process because of the entity containing a numeric attribute that was initially stored in Crate with an `object` type.

INFO:translators.factory:Backend selected for tenant 'orchestracities' is: crate
[2019-08-07 07:14:22,601] ERROR in app: Exception on /v2/notify [POST]
Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
raise value
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/usr/local/lib/python3.6/site-packages/connexion/decorators/decorator.py", line 48, in wrapper
response = function(request)
File "/usr/local/lib/python3.6/site-packages/connexion/decorators/uri_parsing.py", line 143, in wrapper
response = function(request)
File "/usr/local/lib/python3.6/site-packages/connexion/decorators/validation.py", line 172, in wrapper
response = function(request)
File "/usr/local/lib/python3.6/site-packages/connexion/decorators/validation.py", line 347, in wrapper
return function(request)
File "/usr/local/lib/python3.6/site-packages/connexion/decorators/parameter.py", line 126, in wrapper
return function(**kwargs)
File "/src/ngsi-timeseries-api/src/reporter/reporter.py", line 152, in notify
trans.insert(payload, fiware_s, fiware_sp)
File "/src/ngsi-timeseries-api/src/translators/crate.py", line 182, in insert
fiware_servicepath)
File "/src/ngsi-timeseries-api/src/translators/crate.py", line 287, in _insert_entities_of_type
self.cursor.executemany(stmt, entries)
File "/usr/local/lib/python3.6/site-packages/crate/client/cursor.py", line 67, in executemany
self.execute(sql, bulk_parameters=seq_of_parameters)
File "/usr/local/lib/python3.6/site-packages/crate/client/cursor.py", line 54, in execute
bulk_parameters)
File "/usr/local/lib/python3.6/site-packages/crate/client/http.py", line 328, in sql
content = self._json_request('POST', self.path, data=data)
File "/usr/local/lib/python3.6/site-packages/crate/client/http.py", line 448, in _json_request
_raise_for_status(response)
File "/usr/local/lib/python3.6/site-packages/crate/client/http.py", line 187, in _raise_for_status
error_trace=error_trace)
crate.client.exceptions.ProgrammingError: SQLActionException[ColumnValidationException: Validation failed for winddirection: Cannot cast 20 to type object]

**Comment by chicco785** [comment]
@c0c0n3 i think this is fixed by pr #449

**Comment by c0c0n3** [comment]
@chicco785 yep, I'm closing it.
