### ISSUE TITLE
Broken health check if no cache is used

### ISSUE THREAD

**Issue by modularTaco** [orchestracities/ngsi-timeseries-api#446]
**Describe the bug**
If no cache is configured the health check throws an exception:
```
AttributeError: 'NoneType' object has no attribute 'get_health'
```

**To Reproduce**
1. Set `CACHE_GEOCODING` and `CACHE_QUERIES` to `False`
2. Start QL
3. Curl `/health`

**Expected behavior**
Health status should be returned. 

**Additional context**
Full traceback:
```
time=2021-02-04 03:14:06.104 | level=ERROR | corr=None | from=192.168.1.5 | srv=None | subserv=None | op=log_exception | comp=server.wsgi | msg=Exception on /health [GET] | payload=None | thread=139770318101280  | process=36
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.8/site-packages/connexion/decorators/decorator.py", line 48, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.8/site-packages/connexion/decorators/uri_parsing.py", line 144, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.8/site-packages/connexion/decorators/parameter.py", line 121, in wrapper
    return function(**kwargs)
  File "/src/ngsi-timeseries-api/src/reporter/health.py", line 86, in get_health
    res = _check_not_critical(check_cache(), res, 'redis')
  File "/src/ngsi-timeseries-api/src/reporter/health.py", line 28, in check_cache
    return cache.get_health()
AttributeError: 'NoneType' object has no attribute 'get_health'
```

**Comment by c0c0n3** [comment]
@modularTaco thanks for reporting the issue, we'll look into that...
