### ISSUE TITLE
Something wrong happen with some measure

### ISSUE THREAD

**Issue by tzzed** [orchestracities/ngsi-timeseries-api#768]
**Describe the bug**
For some measure I get the following error 

```2024-07-31 16:49:15.216 | File "/src/ngsi-timeseries-api/src/translators/timescale.py", line 67, in read_env |  
-- | -- | --
  |   | 2024-07-31 16:49:15.216 | self.port = r.read(IntVar(POSTGRES_PORT_ENV_VAR, self.port)) |  
  |   | 2024-07-31 16:49:15.216 | File "/src/ngsi-timeseries-api/src/utils/cfgreader.py", line 148, in read |  
  |   | 2024-07-31 16:49:15.216 | return var.read(env_value) |  
  |   | 2024-07-31 16:49:15.216 | File "/src/ngsi-timeseries-api/src/utils/cfgreader.py", line 47, in read |  
  |   | 2024-07-31 16:49:15.216 | return self._do_read(rep) |  
  |   | 2024-07-31 16:49:15.216 | File "/src/ngsi-timeseries-api/src/utils/cfgreader.py", line 70, in _do_read |  
  |   | 2024-07-31 16:49:15.216 | return int(rep) |  
  |   | 2024-07-31 16:49:15.216 | ValueError: invalid literal for int() with base 10: 'tcp://10.X.X.X:5432'
```

**Expected behavior**
the measure should be inserted in Timescale

**Environment (please complete the following information):**
 - **kubernetes**
 - **QuantumLeap** Version 1.0.0
**Additional context**
This happen only with few measure and only in kubernetes environment. Cannot reproduce locally.

**Comment by tzzed** [comment]
The bug fixed after changing configuration. thank you!

**Comment by tzzed** [comment]
But it seems the previous error should be the next one. I think there is some troubleshouting that change the behaviour to the previous one.


```
Traceback (most recent call last): |  
-- | --
  |   | 2024-08-02 11:33:28.142 | File "/usr/local/lib/python3.8/site-packages/pg8000/legacy.py", line 252, in execute |  
  |   | 2024-08-02 11:33:28.142 | self._context = self._c.execute_unnamed( |  
  |   | 2024-08-02 11:33:28.142 | File "/usr/local/lib/python3.8/site-packages/pg8000/core.py", line 649, in execute_unnamed |  
  |   | 2024-08-02 11:33:28.142 | self.handle_messages(context) |  
  |   | 2024-08-02 11:33:28.142 | File "/usr/local/lib/python3.8/site-packages/pg8000/core.py", line 767, in handle_messages |  
  |   | 2024-08-02 11:33:28.142 | raise self.error |  
  |   | 2024-08-02 11:33:28.142 | pg8000.exceptions.DatabaseError: {'S': 'ERROR', 'V': 'ERROR', 'C': '22P02', 'M': 'invalid input syntax for type integer: "50.0"', 'W': "unnamed portal parameter $7 = '...'", 'F': 'numutils.c', 'L': '232', 'R': 'pg_strtoint32'} |  
  |   | 2024-08-02 11:33:28.142 |   |  
  |   | 2024-08-02 11:33:28.142 | During handling of the above exception, another exception occurred: |  
  |   | 2024-08-02 11:33:28.142 |   |  
  |   | 2024-08-02 11:33:28.142 | Traceback (most recent call last): |  
  |   | 2024-08-02 11:33:28.142 | File "/src/ngsi-timeseries-api/src/translators/sql_translator.py", line 366, in _insert_entity_rows |  
  |   | 2024-08-02 11:33:28.142 | res = self.cursor.executemany(stmt, batch) |  
  |   | 2024-08-02 11:33:28.142 | File "/usr/local/lib/python3.8/site-packages/pg8000/legacy.py", line 304, in executemany |  
  |   | 2024-08-02 11:33:28.142 | self.execute(operation, parameters) |  
  |   | 2024-08-02 11:33:28.142 | File "/usr/local/lib/python3.8/site-packages/pg8000/legacy.py", line 279, in execute |  
  |   | 2024-08-02 11:33:28.142 | raise cls(msg) |  
  |   | 2024-08-02 11:33:28.142 | pg8000.dbapi.ProgrammingError: {'S': 'ERROR', 'V': 'ERROR', 'C': '22P02', 'M': 'invalid input syntax for type integer: "50.0"', 'W': "unnamed portal parameter $7 = '...'", 'F': 'numutils.c', 'L': '232', 'R': 'pg_strtoint32'}
```

**Comment by tzzed** [comment]
OK I finally found the problem, the POSTGRES_PORT was changed in the configuration.
